
#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

	[types.stone_type]

		[types.stone_type.alexscaves]
			limestone = true
			galena = true
			radrock = true
			abyssmarine = true
			guanostone = true
			gingerbread = true

		[types.stone_type.dungeons_and_combat]
			bronze = true

		[types.stone_type.eeeabsmobs]
			voidshard = true

		[types.stone_type.legendary_monsters]
			cloud = true
			enderstone = true

	[types.wood_type]

		[types.wood_type.dungeons_and_combat]
			elden_oak = true

		[types.wood_type.eeeabsmobs]
			blighted_oak = true

		[types.wood_type.cataclysm]
			chorus = true

		[types.wood_type.alexscaves]
			pewen = true
			thornwood = true

	[types.leaves_type]

		[types.leaves_type.alexscaves]
			ancient = true

#Disables specific entries
[entries]

	[entries.stone_type]

		[entries.stone_type.waystones]
			waystone = true

		[entries.stone_type.mcwpaths]
			running_bond = true
			mossy_crystal_floor = true
			mossy_windmill_weave_slab = true
			mossy_windmill_weave_path = true
			mossy_windmill_weave = true
			mossy_crystal_floor_path = true
			flagstone_slab = true
			mossy_running_bond = true
			crystal_floor = true
			mossy_flagstone = true
			windmill_weave_slab = true
			mossy_crystal_floor_slab = true
			flagstone_path = true
			mossy_strewn_rocky_path = true
			mossy_running_bond_path = true
			running_bond_path = true
			crystal_floor_path = true
			strewn_rocky_path = true
			windmill_weave = true
			mossy_flagstone_slab = true
			running_bond_slab = true
			windmill_weave_path = true
			mossy_flagstone_path = true
			mossy_running_bond_slab = true
			flagstone = true
			crystal_floor_slab = true

		[entries.stone_type.mcwroofs]
			top_roof = true
			bricks_attic_roof = true
			lower_roof = true
			upper_steep_roof = true
			steep_roof = true
			roof = true
			bricks_steep_roof = true
			bricks_roof = true
			bricks_lower_roof = true
			upper_lower_roof = true
			bricks_top_roof = true
			attic_roof = true
			bricks_upper_steep_roof = true
			bricks_upper_lower_roof = true

		[entries.stone_type.mcwstairs]
			mossy_brick_railing = true
			brick_skyline_stairs = true
			brick_bulk_stairs = true
			mossy_brick_balcony = true
			brick_terrace_stairs = true
			mossy_brick_loft_stairs = true
			brick_loft_stairs = true
			mossy_brick_platform = true
			brick_railing = true
			brick_compact_stairs = true
			brick_balcony = true
			brick_platform = true
			mossy_brick_skyline_stairs = true
			mossy_brick_compact_stairs = true
			mossy_brick_terrace_stairs = true
			mossy_brick_bulk_stairs = true

		[entries.stone_type.mcwbridges]
			balustrade_bricks_bridge = true
			mossy_bridge_pier = true
			mossy_brick_bridge = true
			bridge_pier = true
			mossy_bridge_stair = true
			balustrade_mossy_bricks_bridge = true
			brick_bridge_stair = true
			bridge = true
			brick_bridge = true

		[entries.stone_type.mcwfences]
			modern_wall = true
			modern_brick_wall = true
			railing_gate = true
			grass_topped_wall = true
			railing_wall = true
			railing_brick_wall = true
			brick_railing_gate = true
			pillar_wall = true

		[entries.stone_type.mcwwindows]
			pane_window = true
			window2 = true
			brick_arrow_slit = true
			four_window = true
			brick_gothic = true
			window = true

	[entries.wood_type]

		[entries.wood_type.mcwroofs]
			planks_upper_steep_roof = true
			top_roof = true
			lower_roof = true
			planks_roof = true
			upper_steep_roof = true
			steep_roof = true
			upper_lower_roof = true
			attic_roof = true
			planks_upper_lower_roof = true
			roof = true
			planks_attic_roof = true
			planks_top_roof = true
			planks_steep_roof = true
			planks_lower_roof = true

		[entries.wood_type.mcwfurnitures]
			stripped_glass_table = true
			stripped_desk = true
			stripped_double_kitchen_cabinet = true
			end_table = true
			stool_chair = true
			stripped_kitchen_sink = true
			stripped_lower_triple_drawer = true
			stripped_drawer_counter = true
			bookshelf_drawer = true
			double_drawer = true
			stripped_coffee_table = true
			stripped_counter = true
			stripped_striped_chair = true
			covered_desk = true
			stripped_stool_chair = true
			stripped_modern_wardrobe = true
			cupboard_counter = true
			stripped_covered_desk = true
			stripped_kitchen_cabinet = true
			coffee_table = true
			glass_table = true
			stripped_cupboard_counter = true
			stripped_triple_drawer = true
			stripped_chair = true
			stripped_double_drawer_counter = true
			stripped_modern_desk = true
			stripped_bookshelf_cupboard = true
			modern_wardrobe = true
			lower_bookshelf_drawer = true
			striped_chair = true
			double_kitchen_cabinet = true
			stripped_large_drawer = true
			wardrobe = true
			kitchen_sink = true
			modern_desk = true
			stripped_lower_bookshelf_drawer = true
			stripped_end_table = true
			drawer = true
			stripped_bookshelf_drawer = true
			stripped_glass_kitchen_cabinet = true
			stripped_bookshelf = true
			modern_chair = true
			chair = true
			stripped_table = true
			double_drawer_counter = true
			drawer_counter = true
			kitchen_cabinet = true
			counter = true
			stripped_modern_chair = true
			bookshelf_cupboard = true
			table = true
			desk = true
			stripped_double_wardrobe = true
			stripped_double_drawer = true
			triple_drawer = true
			lower_triple_drawer = true
			glass_kitchen_cabinet = true
			bookshelf = true
			stripped_wardrobe = true
			large_drawer = true
			double_wardrobe = true
			stripped_drawer = true

		[entries.wood_type.mcwwindows]
			louvered_shutter = true
			plank_pane_window = true
			curtain_rod = true
			plank_four_window = true
			stripped_log_window2 = true
			log_parapet = true
			window2 = true
			stripped_log_four_window = true
			stripped_log_window = true
			plank_window = true
			plank_window2 = true
			pane_window = true
			stripped_pane_window = true
			four_window = true
			plank_parapet = true
			blinds = true
			window = true
			shutter = true

		[entries.wood_type.mcwdoors]
			japanese2_door = true
			tropical_door = true
			barn_glass_door = true
			four_panel_door = true
			beach_door = true
			waffle_door = true
			japanese_door = true
			stable_door = true
			modern_door = true
			nether_door = true
			stable_head_door = true
			cottage_door = true
			western_door = true
			paper_door = true
			bamboo_door = true
			swamp_door = true
			glass_door = true
			barn_door = true
			mystic_door = true
			whispering_door = true
			bark_glass_door = true
			classic_door = true

		[entries.wood_type.mcwfences]
			highley_gate = true
			picket_fence = true
			stockade_fence = true
			wired_fence = true
			horse_fence = true
			pyramid_gate = true

		[entries.wood_type.mcwbridges]
			bridge_pier = true
			rope_bridge = true
			log_bridge_middle = true
			rope_bridge_stair = true
			log_bridge_stair = true
			rail_bridge = true

		[entries.wood_type.mcwstairs]
			terrace_stairs = true
			compact_stairs = true
			balcony = true
			loft_stairs = true
			railing = true
			platform = true
			skyline_stairs = true
			bulk_stairs = true

		[entries.wood_type.mcwpaths]
			planks_path = true

	[entries.leaves_type]

		[entries.leaves_type.mcwfences]
			hedge = true

